### ISSUE TITLE
Demo script

### ISSUE THREAD

**Issue by alexkwood** [MarrLiss/backbone-websql#1]
Hello,

thanks for creating the websql persistance adapter.

Any chance of a sample html page to see it in action ?

Thanks,
Alex

**Comment by MarrLiss** [comment]
I haven't finished an example yet, I hope I'll commit it soon.

**Comment by jtmkrueger** [comment]
Yea an example would be great.  I'm trying to figure out what model.store should look like.  Even if the README was updated to show some usage examples, that would be fantastic. I changed sync to dbSync to fix a collision I was having with backbone's sync method...

**Comment by MarrLiss** [comment]
I added an example (Localtodos by Jérôme Gravel-Niquet). I hope, that it will be helpful for you.
