### ISSUE TITLE
Error en update function

### ISSUE THREAD

**Issue by jonathannaguin** [MarrLiss/backbone-websql#16]
The `update` function has an error when creates the SQL sentence. The update SQL syntax is:

```
UPDATE table_reference
SET col_name1='expr1' , col_name2='expr2' 
WHERE where_condition
```

But in the `update` function is creating something like

```
UPDATE table_reference
SET col_name1='expr1' AND col_name2='expr2' 
WHERE where_condition
```

Notice the **AND** instead of a comma.

The fix is really easy, change `setStmts.join(" AND ")` in line 136 with `setStmts.join(" ,")`.

Thank you.

**Comment by josefadamcik** [comment]
Thank you for reporting.
