### ISSUE TITLE
collection.fetch() results in Uncaught TypeError: Cannot read property 'undefined' of undefined 

### ISSUE THREAD

**Issue by elliotcw** [MarrLiss/backbone-websql#4]
When I perform a fetch on a collection, this bit of code get hits (ln 135):

``` javascript
case "read":    (model.attributes[model.idAttribute] ? store.find(model,success,error) : store.findAll(model, success, error)); 
```

and results in:

``` javascript
Uncaught TypeError: Cannot read property 'undefined' of undefined 
```

Now as far as I can see the collection has no attributes, so when it looks for the model.idAttribute'th item it throws an error.

I fixed by:

``` javascript
case "read":    (((model.attributes)&&(model.attributes[model.idAttribute])) ? store.find(model,success,error) : store.findAll(model, success, error)); 
```

Should the collection object have an attributes property?

**Comment by MarrLiss** [comment]
You are right. I sent fix for it to the Github. Thank you. :)
